name: CI

on:
  push:
    paths-ignore:
      - '**/*.md'
  pull_request:
    paths-ignore:
      - '**/*.md'

# First build on Linux and Windows with JDK 21
# Then run tests with various Gradle and JDK versions
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'

      - uses: gradle/actions/setup-gradle@v5
        with:
          build-scan-publish: true
          build-scan-terms-of-use-url: "https://gradle.com/help/legal-terms-of-use"
          build-scan-terms-of-use-agree: "yes"

      - name: Build with Gradle
        id: gradle-build
        run: ./gradlew build

      - name: Store reports
        if: always() && (steps.gradle-build.outcome == 'success' || steps.gradle-build.outcome == 'failure')
        uses: actions/upload-artifact@v4
        with:
          name: linux-reports
          path: build/reports/

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'

      - uses: gradle/actions/setup-gradle@v5
        with:
          build-scan-publish: true
          build-scan-terms-of-use-url: "https://gradle.com/help/legal-terms-of-use"
          build-scan-terms-of-use-agree: "yes"

      - name: Build with Gradle
        id: gradle-build
        run: ./gradlew build

      - name: Store reports
        if: always() && (steps.gradle-build.outcome == 'success' || steps.gradle-build.outcome == 'failure')
        uses: actions/upload-artifact@v4
        with:
          name: windows-reports
          path: build/reports/

  # Test using a JDK version that's compatible with all supported versions (JDK 17)
  # but keep building with the same JDK (21) so it can benefit from build cache.
  test-gradle:
    needs: linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        gradle: [ '9.2.0-rc-2', '9.1.0', '9.0.0', '8.13', '8.12.1', '8.11.1', '8.10.2', '8.9', '8.8', '8.7', '8.6', '8.5', '8.4' ]
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: |
            17
            21

      - name: Setup environment
        run: |
          echo "org.gradle.java.installations.auto-download=false" | tee -a gradle.properties
          echo "org.gradle.java.installations.fromEnv=JAVA_HOME_17_X64" | tee -a gradle.properties

      - uses: gradle/actions/setup-gradle@v5
        with:
          build-scan-publish: true
          build-scan-terms-of-use-url: "https://gradle.com/help/legal-terms-of-use"
          build-scan-terms-of-use-agree: "yes"

      - name: Build with Gradle
        id: gradle-build
        run: ./gradlew functionalTest "-Ptest.gradle-version=${{ matrix.gradle }}" "-Ptest.java-toolchain=17"

      - name: Store reports
        if: always() && (steps.gradle-build.outcome == 'success' || steps.gradle-build.outcome == 'failure')
        uses: actions/upload-artifact@v4
        with:
          name: gradle-${{ matrix.gradle }}-tests
          path: build/reports/tests/functionalTest/

  test-jdk:
    needs: linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # There's no combination of jooq and h2 that's compatible with Java 8
        java: [ 11, 17 ]
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: |
            ${{ matrix.java }}
            21

      - name: Setup environment
        run: |
          echo "org.gradle.java.installations.auto-download=false" | tee -a gradle.properties
          echo "org.gradle.java.installations.fromEnv=JAVA_HOME_${{ matrix.java }}_X64" | tee -a gradle.properties

      - uses: gradle/actions/setup-gradle@v5
        with:
          build-scan-publish: true
          build-scan-terms-of-use-url: "https://gradle.com/help/legal-terms-of-use"
          build-scan-terms-of-use-agree: "yes"

      - name: Build with Gradle
        id: gradle-build
        run: ./gradlew functionalTest "-Ptest.java-toolchain=${{ matrix.java }}"

      - name: Store reports
        if: always() && (steps.gradle-build.outcome == 'success' || steps.gradle-build.outcome == 'failure')
        uses: actions/upload-artifact@v4
        with:
          name: jdk-${{ matrix.java }}-tests
          path: build/reports/tests/functionalTest/
